---
galaxy_info:
  author: The Galaxy Project
  description: Setup the basic system-level requirements for running Galaxy.
  company: The Galaxy Project
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies: []
